### ISSUE TITLE
Agregar el propósito de cada archivo en el Readme.md

### ISSUE THREAD

**Issue by paulinabustos** [CodeandoMexico/comunidad#2]
Para saber mejor cómo contribuir a cada archivo, debemos saber su propósito. El Readme ayuda mucho a tener esa información a la mano.

**Comment by darredondort** [comment]
Totalmente, @paulinabustos! Algunos ya tienen descripción en el README, pero hay otros que aún no hemos dicho de qué se tratan o no están en el README.

Les agregaré una pequeña descripción de propósito tanto al README como dentro de todos los documentos para que no haya ninguno vacío del todo.
Gracias! 👊
