### ISSUE TITLE
Agregar plantilla para política de privacidad (de datos)

### ISSUE THREAD

**Issue by defvol** [CodeandoMexico/comunidad#3]
### ¿Cómo funciona hoy la comunidad de Codeando México? Consulta nuestros documentos:

Pon una X entre los corchetes si has hecho lo siguiente:
* [x] He leído y suscribo el Código de Conducta de la comunidad.
* [x] He leído la Guía de Contribución
* [x] He leído documentos escenciales sobre el propósito de Codeando México como el Manifiesto, Governanza y la misión y valores contenidos en el README.

### Descripción

No encuentro una guía o estándar acordado por la comunidad para el manejo responsable de datos personales (i.e. una política de privacidad).

### Propuesta

Usemos este _thread_ para delinear y generar un borrador de lo que sería un _template_ de privacidad acorde a los valores de la comunidad.

### Impacto

- Definimos las expectativas y estrategias del uso de datos personales
- Podemos tener acceso completo a APIs de servicios que exigen este requerimiento

[¿Cómo cambiaría la forma en que se organiza y colabora la comunidad si pone en marcha esta propuesta?]

- Al definir las expectativas del uso de la información de los usuarios de nuestros servicios, nos comprometemos a cuidar sus datos.

**Comment by defvol** [comment]
Relacionado https://github.com/CodeandoMexico/terremoto-cdmx/issues/124

**Comment by miguelsalazar** [comment]
Me parece súper importante trabajar en un documento así, una política de privacidad que sirva tanto para las herramientas internas u oficiales del equipo (por ejemplo: datamx), como para las aplicaciones que desarrolle la comunidad. Esta política, igual que los valores, código de conducta, manifiesto y la misión, es un contrato vinculante entre el equipo y la comunidad: el equipo espera que la comunidad incorpore esa política de privacidad (en este caso) en sus aplicaciones, y la comunidad espera que el equipo haga lo mismo.

El pirate pad ligado en el issue relacionado me parece bueno, aunque muy específico para el contexto de [#SISMOMX](http://github.com/CodeandoMexico/terremoto-cdmx) (¿por qué 72 horas?). De las referencias que citas, la de @muddylemon me parece sencilla y al punto. Quizá podamos partir de ahí y abrirla a la comunidad.

(A propósito: también nos faltan mecanismos de deliberación en la comunidad.)
